language: node_js
node_js:
- '10'
script:
- yarn install
- yarn build
- yarn setup
cache: yarn
branches:
  only:
  - master
after_success:
  - npm i -g firebase-ci
  - npm i -g firebase-tools
  - firebase-ci deploy
