language: node_js
node_js:
- '10'
cache: yarn
branches:
  only:
  - master
script:
  - echo script completed
before_deploy:
  - npm i -g firebase-tools
deploy:
  provider: script
  script: "yarn deploy:functions || yarn deploy:functions"
  skip_cleanup: true
