language: node_js
node_js:
  - '10'
script:
  - yarn install
  - yarn build
  - yarn setup
deploy:
  provider: firebase
  token:
    secure: WCXL7P9Hp724bahxhAIaMCCpETswWF3wdMoHlzvPXSJrxJYsLADiiKhnU39FT8bf49/fj0Us9fzhzp90gll8cIQ44nJtPjFPZeR1ygJelR2qZ2WU8A2AzPw16hHx7euf5g0uWretho6bVKV0OfKkOyQtsx4rpRtp/EfSuGx5yL9ml2GDZcezOwKAAiWvs0DH6r6JMT1DMRrJqQsbgNBc3xNc3mYZmNv/CBkYYyMrfeEDPiQiRW389aTYt8cNZwnxpumODxVbpw9q30POTZ4Nd60TkcbdNicD9iOYO1mjWw3CTqcnO+5XWuYA1zAFyuv9/4Bikos1zGj2TljsyXdYiEVyg2Njm/vGE6h4+BglAGgvpzcbMh+4GISJPQAT9qP8GJKef846hGOfylk5U9TSUQSw+wovMf5eQ4lAjJrWxiC+pQTCqIxYmbLni5+zUqqvKxjAJQ7JpelR5+oehrjL35h2ca/VAZc5o2tbto4fKzk42dzPz+ba9qv4Lbfs2gt4nYnW75qIdm5RlVHNuQ9IBjgxlepd5UaMTpSXSWqUADvTkONTwQOySFFA5YqtWVnfi3fug9j73OR9GtliK043T1H7eF8EGOof5QAVYoqtfd+mrOI4XljiddgRplU+qiB9Rw7CWSW3o9ot9gqf02UditfwHPRbegCGusd1mY2zQj8=
